openapi: 3.0.3
info:
  version: 1.0.0
  title: Wikalpa
  description: API documentation for the Wikalpa project.
  termsOfService: https://opensource.org/ToS
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /auth/register:
    post:
      tags:
        - Auth
      security: []
      summary: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                      example: john.doe
                    password:
                      type: string
                      example: super-strong-password
                    password_confirmation:
                      type: string
                      example: super-strong-password
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      user:
                        $ref: "#/components/schemas/User"
                      token:
                        $ref: "#/components/schemas/Token"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /auth/login:
    post:
      tags:
        - Auth
      security: []
      summary: Login into an existing user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: john.doe
                password:
                  type: string
                  example: super-strong-password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      user:
                        $ref: "#/components/schemas/User"
                      token:
                        $ref: "#/components/schemas/Token"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /communities:
    post:
      tags:
        - Community
      summary: Create a new community.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - community
              properties:
                community:
                  type: object
                  properties:
                    name:
                      type: string
                      example: programmer.humor
                    description:
                      type: string
                      example: css is programming language
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      community:
                        $ref: "#/components/schemas/Community"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /communities/{id}:
    put:
      tags:
        - Community
      summary: Update a community.
      parameters:
        - $ref: "#/components/parameters/Identifier"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - community
              properties:
                community:
                  type: object
                  properties:
                    name:
                      type: string
                      example: programmer.humor
                    description:
                      type: string
                      example: css is programming language
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      community:
                        $ref: "#/components/schemas/Community"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /communities/{community_id}/join:
    post:
      tags:
        - Member
      summary: Join a community.
      parameters:
        - $ref: "#/components/parameters/IdentifierCommunity"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      member:
                        $ref: "#/components/schemas/Member"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /communities/{community_id}/leave:
    delete:
      tags:
        - Member
      summary: Leave a community.
      parameters:
        - $ref: "#/components/parameters/IdentifierCommunity"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      member:
                        $ref: "#/components/schemas/Member"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /communities/{community_id}/posts:
    post:
      tags:
        - Post
      summary: Create a new post.
      parameters:
        - $ref: "#/components/parameters/IdentifierCommunity"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      post:
                        $ref: "#/components/schemas/Post"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /posts/{id}:
    put:
      tags:
        - Post
      summary: Update a post.
      parameters:
        - $ref: "#/components/parameters/Identifier"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      post:
                        $ref: "#/components/schemas/Post"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /posts/{post_id}/comments:
    post:
      tags:
        - Comment
      summary: Create a new comment.
      parameters:
        - $ref: "#/components/parameters/IdentifierPost"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      comment:
                        $ref: "#/components/schemas/Comment"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /comments/{id}:
    put:
      tags:
        - Comment
      summary: Update a comment.
      parameters:
        - $ref: "#/components/parameters/Identifier"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      comment:
                        $ref: "#/components/schemas/Comment"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
  /users/{id}:
    put:
      tags:
        - User
      summary: Update a user.
      parameters:
        - $ref: "#/components/parameters/Identifier"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - password_confirmation
              properties:
                username:
                  type: string
                  example: john.doe
                password:
                  type: string
                  example: super-strong-password
                password_confirmation:
                  type: string
                  example: super-strong-password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      user:
                        $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
security:
  - BearerAuth: []
tags:
  - name: Auth
    description: Endpoints related for authentication and authorization.
  - name: Community
    description: Endpoints related for community resources.
  - name: Member
    description: Endpoints related for member resources.
  - name: Post
    description: Endpoints related for post resources.
  - name: Comment
    description: Endpoints related for comment resources.
  - name: User
    description: Endpoints related for user resources.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    Identifier:
      in: path
      name: id
      required: true
      schema:
        type: integer
        example: 1
    IdentifierCommunity:
      in: path
      name: community_id
      required: true
      schema:
        type: integer
        example: 1
    IdentifierPost:
      in: path
      name: post_id
      required: true
      schema:
        type: integer
        example: 1
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        post_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        body:
          type: string
          example: just setting up my wklp
        created_at:
          type: string
          example: "2021-12-12 12:12:12"
        updated_at:
          type: string
          example: "2021-12-12 12:12:12"
    Community:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: programmer.humor
        description:
          type: string
          example: css is programming language
        created_at:
          type: string
          example: "2021-12-12 12:12:12"
        updated_at:
          type: string
          example: "2021-12-12 12:12:12"
    Member:
      type: object
      properties:
        id:
          type: integer
          example: 1
        community_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        created_at:
          type: string
          example: "2021-12-12 12:12:12"
        updated_at:
          type: string
          example: "2021-12-12 12:12:12"
    Post:
      type: object
      properties:
        id:
          type: integer
          example: 1
        community_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        body:
          type: string
          example: just setting up my wklp
        created_at:
          type: string
          example: "2021-12-12 12:12:12"
        updated_at:
          type: string
          example: "2021-12-12 12:12:12"
    Token:
      type: string
      example: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.GRKevXZcuSlwDfjKYXB_plUM4m5Pu4S_VgPsFj1bxrI
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: john.doe
        created_at:
          type: string
          example: "2021-12-12 12:12:12"
        updated_at:
          type: string
          example: "2021-12-12 12:12:12"
  responses:
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Forbidden
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Not Found
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Unauthorized
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Unprocessable Entity
              errors:
                type: object
                properties:
                  attribute:
                    type: array
                    items:
                      type: string
                      example: error message
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: http://localhost:3001/api/v1
    description: Local-Docker server
