name: Build

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: rgxcp
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rgxcp/wikalpa:latest
