name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup Bundler
        run: gem install bundler:2.2.33 --no-document
      - name: Setup Bundle
        run: bundle config set without development
      - name: Install dependencies
        run: bundle install
      - name: Setup database
        run: bin/rails db:setup
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
      - name: Run test
        run: |
          echo "Running models test"
          bundle exec rspec spec/models
          echo "Running workers test"
          bundle exec rspec spec/workers
          echo "Running routing test"
          bundle exec rspec/routing
          echo "Running requests test"
          bundle exec rspec/requests
        env:
          JWT_KEY: jwt
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
      - name: Upload coverage report result to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage/coverage.xml
